name: maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Disabled for Java 10 due to Java compiler bug
        java: [ 8, 9, 11, 12, 13, 14, 15, 16, 17 ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - run: mvn -B package --file pom.xml

